# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_spidertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_info', models.CharField(max_length=64)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='spidertable',
            name='pro_info',
        ),
    ]
