# Generated by Django 2.1.3 on 2018-12-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_spiderproduct_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportinfo',
            old_name='author',
            new_name='authorName',
        ),
        migrations.RenameField(
            model_name='reportinfo',
            old_name='test_type',
            new_name='backInfo',
        ),
        migrations.RenameField(
            model_name='reportinfo',
            old_name='doc_lis',
            new_name='coverAge',
        ),
        migrations.RenameField(
            model_name='reportinfo',
            old_name='scope',
            new_name='testStrategy',
        ),
        migrations.RenameField(
            model_name='reportinfo',
            old_name='back_info',
            new_name='testType',
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='emailContent',
            field=models.CharField(default='略', max_length=128),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='referenceFile',
            field=models.CharField(default='略', max_length=64),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='testConclusion',
            field=models.CharField(default='略', max_length=64),
        ),
    ]
