# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0005_auto_20180529_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('device', models.CharField(max_length=16, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('nt', models.IntegerField(choices=[(1, '42区'), (2, '段子'), (3, '图片'), (4, '挨踢1024'), (5, '你问我答')])),
                ('favor_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('times', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='favor',
            field=models.ManyToManyField(to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n', to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cp', to='web.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
    ]
