# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180529_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmsg',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
