# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_reporttemplate_bug_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_info_close', models.TextField(default='略', null=True)),
                ('bug_info_not_close', models.TextField(default='略', null=True)),
                ('pro_info', models.CharField(max_length=64)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
    ]
