# Generated by Django 2.1.3 on 2018-11-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20181127_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinfo',
            name='env_img',
        ),
    ]
