# Generated by Django 2.1.3 on 2018-11-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_reportinfo_env_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equ_env', models.CharField(max_length=64, null=True)),
                ('hr_lis', models.CharField(max_length=128, null=True)),
                ('func_lis', models.CharField(default='略', max_length=128)),
                ('tac_des', models.CharField(default='略', max_length=128)),
                ('tac_from_con', models.CharField(max_length=128, null=True)),
                ('dev_bug', models.CharField(max_length=128, null=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='dev_bug',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='equ_env',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='func_lis',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='hr_lis',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='tac_des',
        ),
        migrations.RemoveField(
            model_name='reportinfo',
            name='tac_from_con',
        ),
    ]
