# Generated by Django 2.1.3 on 2018-12-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20181203_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='testConclusion',
            field=models.CharField(default='略', max_length=128),
        ),
    ]
