# Generated by Django 2.1.3 on 2018-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_reportinfo_testconclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalinfo',
            name='tt_con',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
