# Generated by Django 2.1.3 on 2018-12-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_modalinfo_tt_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalinfo',
            name='func_lis',
        ),
    ]
