# Generated by Django 2.1.3 on 2019-05-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20190529_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertestingtable',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='PertestingTable',
        ),
    ]
