# Generated by Django 2.1.3 on 2019-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_pertestingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingtable',
            name='maxnum',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='oncenum',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
