# Generated by Django 2.1.3 on 2019-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_pertestingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingtable',
            name='maxnum',
            field=models.IntegerField(default=10, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='oncenum',
            field=models.IntegerField(default=2, max_length=16),
        ),
    ]
