# Generated by Django 2.1.3 on 2019-06-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20190605_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertestingtable',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='PertestingTable',
        ),
    ]
