# Generated by Django 2.1.3 on 2019-06-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_pertestingserverstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='cpu_id',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='cpu_sy',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='cpu_us',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='memory_buff',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='memory_cache',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='memory_free',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='procss_b',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='procss_r',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
