# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_auto_20190612_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilesPaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_souceFile_path', models.CharField(max_length=32)),
                ('word_resultFile_path', models.CharField(max_length=32)),
                ('excel_souceFile_path', models.CharField(max_length=32)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
    ]
