# Generated by Django 2.1.3 on 2019-07-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_auto_20190711_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='server_port',
            field=models.IntegerField(default=22),
        ),
    ]
