# Generated by Django 2.1.3 on 2019-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_auto_20190711_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='domain',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='news',
            name='explain',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='news',
            name='icon',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='news',
            name='img_href',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='news',
            name='nt',
            field=models.IntegerField(choices=[(1, '圈内'), (2, '圈外')]),
        ),
    ]
