# Generated by Django 2.1.3 on 2019-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_auto_20190715_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='nt',
            field=models.IntegerField(choices=[(1, '圈外'), (2, '圈内')]),
        ),
    ]
