# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180529_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_line', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('back_info', models.TextField(default='略')),
                ('func_lis', models.CharField(default='略', max_length=128)),
                ('scope', models.CharField(default='略', max_length=128)),
                ('doc_lis', models.CharField(default='略', max_length=128)),
                ('env_img', models.ImageField(default='略', max_length=128, upload_to='')),
                ('equ_env', models.CharField(max_length=64, null=True)),
                ('hr_lis', models.CharField(max_length=128, null=True)),
                ('tac_des', models.CharField(default='略', max_length=128)),
                ('tac_from_con', models.CharField(max_length=128, null=True)),
                ('test_type', models.CharField(default='略', max_length=64)),
                ('bug_info', models.CharField(max_length=128, null=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
    ]
