# Generated by Django 2.1.3 on 2018-12-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20181203_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportinfo',
            old_name='testConclusion',
            new_name='testRisk',
        ),
    ]
