# Generated by Django 2.1.3 on 2019-06-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_pertestingserverstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertestingserverstable',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='PertestingServersTable',
        ),
    ]
