# Generated by Django 2.1.3 on 2019-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_pertestingserverstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='sysLoad_runTime',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='sysLoad_time',
            field=models.CharField(max_length=16),
        ),
    ]
