# Generated by Django 2.1.3 on 2019-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20190612_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='memory_used_per',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='sysLoad_loadLevel_15min',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='sysLoad_loadLevel_1min',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='sysLoad_loadLevel_5min',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pertestingserverstable',
            name='sysLoad_userNum',
            field=models.CharField(max_length=16),
        ),
    ]
