# Generated by Django 2.1.3 on 2019-05-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20190529_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingtable',
            name='method',
            field=models.CharField(default='get', max_length=32),
        ),
    ]
