# Generated by Django 2.1.3 on 2019-07-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_userfilespaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertestingtable',
            name='loop_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='lose_req',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='maxTime',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='maxnum',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='oncenum',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='success_req',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pertestingtable',
            name='total_req',
            field=models.IntegerField(default=0),
        ),
    ]
